version: '3.5'
services:
  reactJS:
    image: piyush102/hms_frontend
    ports:
      - 3000:3000
    container_name: react-js-container
    command: npm start
    depends_on:
      - springboot
  mydb:
    image: mysql:8.0
    expose: 
      - 3301
    ports:
      - 3301:3301
    container_name: database_container
    volumes:
      - mysql-data4:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hospital_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3301
  springboot:
    image: piyush102/hms_backend
    ports:
      - 4000:4000
    container_name: springboot_container_sql1
#    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3301/hospital_management
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mydb
volumes:
  mysql-data4:
