---
- name: run containers
  hosts: ubuntu18
  become: true

  tasks:
    - name: copy docker file
      copy:
        src: docker-compose.yml
        dest: docker-compose.yml
    - name: shell docker
      shell:
        cmd: docker-compose down

    - name: shell docker
      shell:
        cmd: docker-compose up
